# set(CMAKE_C_COMPILER )
# set(CMAKE_CXX_COMPILER )

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /DWIN32 /D_WINDOWS /W3 /O2 /wd4267 /wd4251")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /DWIN32 /D_WINDOWS /W3 /GR /EHsc /O2 /wd4267 /wd4251")


add_compile_definitions(_CRT_SECURE_NO_WARNINGS _USE_MATH_DEFINES NOMINMAX)

set(CMAKE_DEBUG_POSTFIX "d")
set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} /DWIN32 /D_WINDOWS /W3 /Od")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /DWIN32 /D_WINDOWS /W3 /GR /EHsc /Od")
