del "%OSGEO4W_STARTMENU%\QGIS Desktop @version@ with GRASS @grassversion@.lnk"
rmdir "%OSGEO4W_STARTMENU%"
del "%OSGEO4W_DESKTOP%\QGIS Desktop @version@ with GRASS @grassversion@.lnk"
rmdir "%OSGEO4W_DESKTOP%"
del "%OSGEO4W_ROOT%\bin\@package@-grass@.bat"
del "%OSGEO4W_ROOT%\bin\@package@-bin-grass.exe"
del "%OSGEO4W_ROOT%\bin\@package@-bin-grass.vars"
del "%OSGEO4W_ROOT%\bin\@package@-bin-grass.env"
del /s /q "%OSGEO4W_ROOT%\apps\@package@\grass\*.pyc"
